apiVersion: apps/v1
kind: Deployment
metadata:
  name: example4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example4
  template:
    metadata:
      labels:
        app: example4
    spec:
      containers:
        - name: example4
          image: bekovkanat/example4:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: 'postgres://postgres:Zxcvbnm123@host:5432/example4'

---
apiVersion: v1
kind: Service
metadata:
  name: example4-service
spec:
  type: NodePort
  selector:
    app: example4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31111 # Можно указать порт от 30000 до 32767
